import type { ConversationBookmark } from './bookmark.types'

// Mock data for conversation bookmarks
export const MOCK_BOOKMARKS: Record<string, ConversationBookmark> = {
  'bookmark-1': {
    id: 'bookmark-1',
    userId: 'user-you',
    conversationId: 'conv-mission-planning',
    messageId: 'msg-1738250200',
    name: 'Critical Mission Timeline',
    description: 'Key discussion about Mars mission timeline adjustments',
    color: '#ff6b6b',
    tags: ['mars', 'timeline', 'critical'],
    metadata: {
      importance: 'high',
      category: 'planning',
      reviewed: true,
    },
    createdAt: new Date('2024-01-15T10:30:00Z'),
    updatedAt: new Date('2024-01-15T10:30:00Z'),
  },
  'bookmark-2': {
    id: 'bookmark-2',
    userId: 'user-you',
    conversationId: 'conv-technical-review',
    messageId: 'msg-1738250300',
    name: 'Equipment Specifications',
    description: 'Important technical details about rover specifications',
    color: '#4ecdc4',
    tags: ['equipment', 'specs', 'rover'],
    metadata: {
      importance: 'medium',
      category: 'technical',
      reviewed: false,
    },
    createdAt: new Date('2024-01-16T14:45:00Z'),
    updatedAt: new Date('2024-01-16T14:45:00Z'),
  },
  'bookmark-3': {
    id: 'bookmark-3',
    userId: 'user-you',
    conversationId: 'conv-team-standup',
    messageId: 'msg-1738250400',
    name: 'Action Items',
    description: 'List of action items from the team standup',
    color: '#45b7d1',
    tags: ['action-items', 'standup', 'team'],
    metadata: {
      importance: 'high',
      category: 'meeting',
      reviewed: true,
    },
    createdAt: new Date('2024-01-17T09:15:00Z'),
    updatedAt: new Date('2024-01-17T09:15:00Z'),
  },
  'bookmark-4': {
    id: 'bookmark-4',
    userId: 'user-you',
    conversationId: 'conv-research-discussion',
    messageId: 'msg-1738250500',
    name: 'Research Findings',
    description: 'Key insights from the latest research on Martian soil',
    color: '#f7dc6f',
    tags: ['research', 'soil', 'findings'],
    metadata: {
      importance: 'medium',
      category: 'research',
      reviewed: false,
    },
    createdAt: new Date('2024-01-18T16:20:00Z'),
    updatedAt: new Date('2024-01-18T16:20:00Z'),
  },
  'bookmark-5': {
    id: 'bookmark-5',
    userId: 'user-you',
    conversationId: 'conv-project-updates',
    messageId: 'msg-1738250600',
    name: 'Budget Approval',
    description: 'Message about budget approval for the next phase',
    color: '#bb8fce',
    tags: ['budget', 'approval', 'phase2'],
    metadata: {
      importance: 'high',
      category: 'finance',
      reviewed: true,
    },
    createdAt: new Date('2024-01-19T11:30:00Z'),
    updatedAt: new Date('2024-01-19T11:30:00Z'),
  },
  'bookmark-6': {
    id: 'bookmark-6',
    userId: 'user-you',
    conversationId: 'conv-mission-planning',
    messageId: 'msg-1738250700',
    name: 'Risk Assessment',
    description: 'Discussion about potential risks and mitigation strategies',
    tags: ['risk', 'assessment', 'mitigation'],
    metadata: {
      importance: 'high',
      category: 'planning',
      reviewed: false,
    },
    createdAt: new Date('2024-01-20T08:45:00Z'),
    updatedAt: new Date('2024-01-20T08:45:00Z'),
  },
  'bookmark-7': {
    id: 'bookmark-7',
    userId: 'user-john',
    conversationId: 'conv-technical-review',
    messageId: 'msg-1738250800',
    name: 'Code Review Feedback',
    description: 'Important feedback from code review session',
    color: '#96ceb4',
    tags: ['code-review', 'feedback', 'development'],
    metadata: {
      importance: 'medium',
      category: 'development',
      reviewed: true,
    },
    createdAt: new Date('2024-01-21T13:20:00Z'),
    updatedAt: new Date('2024-01-21T13:20:00Z'),
  },
  'bookmark-8': {
    id: 'bookmark-8',
    userId: 'user-sarah',
    conversationId: 'conv-team-standup',
    messageId: 'msg-1738250900',
    name: 'Deployment Schedule',
    description: 'Schedule for the upcoming deployment cycle',
    color: '#feca57',
    tags: ['deployment', 'schedule', 'release'],
    metadata: {
      importance: 'high',
      category: 'deployment',
      reviewed: false,
    },
    createdAt: new Date('2024-01-22T10:15:00Z'),
    updatedAt: new Date('2024-01-22T10:15:00Z'),
  },
}
