import type { Participant } from './participant.types'

// Mock data for participant lists - references the same data as individual participants
export const MOCK_PARTICIPANTS_LIST: Record<string, Participant> = {
  'user-you': {
    id: 'user-you',
    name: 'You',
    email: 'user@example.com',
    role: 'Individual Contributor',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date(),
  },
  'user-john': {
    id: 'user-john',
    name: 'John',
    email: 'john@example.com',
    role: 'Frontend Developer',
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date(),
  },
  'user-sarah': {
    id: 'user-sarah',
    name: 'Sarah',
    email: 'sarah@example.com',
    role: 'Senior Frontend Developer',
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date(),
  },
  'user-mike': {
    id: 'user-mike',
    name: 'Mike',
    email: 'mike@example.com',
    role: 'Backend Developer',
    createdAt: new Date('2024-01-04'),
    updatedAt: new Date(),
  },
  'user-emma': {
    id: 'user-emma',
    name: 'Emma',
    email: 'emma@example.com',
    role: 'Full Stack Developer',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date(),
  },
  'user-alex': {
    id: 'user-alex',
    name: 'Alex',
    email: 'alex@example.com',
    role: 'Project Manager',
    createdAt: new Date('2024-01-06'),
    updatedAt: new Date(),
  },
  'user-david': {
    id: 'user-david',
    name: 'David',
    email: 'david@example.com',
    role: 'DevOps Engineer',
    createdAt: new Date('2024-01-07'),
    updatedAt: new Date(),
  },
  'user-lisa': {
    id: 'user-lisa',
    name: 'Lisa',
    email: 'lisa@example.com',
    role: 'UI/UX Designer',
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date(),
  },
  'user-mark': {
    id: 'user-mark',
    name: 'Mark',
    email: 'mark@example.com',
    role: 'Team Lead',
    createdAt: new Date('2024-01-09'),
    updatedAt: new Date(),
  },
  'user-anna': {
    id: 'user-anna',
    name: 'Anna',
    email: 'anna@example.com',
    role: 'QA Engineer',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date(),
  },
}
