import type { Thread } from './thread.types'

// Mock data for thread lists - references the same data as individual threads
export const MOCK_THREADS_LIST: Record<string, Thread> = {
  'thread-1': {
    id: 'thread-1',
    title: 'Project Architecture Discussion',
    content: "Let's discuss the overall architecture approach for the new project features.",
    chatChannelId: 'chat-team-general',
    authorId: 'user-you',
    messageCount: 15,
    lastMessageAt: new Date('2024-01-12T10:30:00Z'),
    isLocked: false,
    isPinned: true,
    tags: ['architecture', 'discussion', 'important'],
    createdAt: new Date('2024-01-10T09:00:00Z'),
    updatedAt: new Date('2024-01-12T10:30:00Z'),
  },
  'thread-2': {
    id: 'thread-2',
    title: 'Frontend Component Standards',
    content: 'Guidelines for creating consistent and reusable React components.',
    chatChannelId: 'chat-frontend-dev',
    authorId: 'user-john',
    messageCount: 8,
    lastMessageAt: new Date('2024-01-11T14:45:00Z'),
    isLocked: false,
    isPinned: false,
    tags: ['frontend', 'components', 'standards'],
    createdAt: new Date('2024-01-09T16:20:00Z'),
    updatedAt: new Date('2024-01-11T14:45:00Z'),
  },
  'thread-3': {
    id: 'thread-3',
    title: 'API Design Patterns',
    content: 'Discussion on best practices for API design and implementation.',
    chatChannelId: 'chat-backend-dev',
    authorId: 'user-sarah',
    messageCount: 22,
    lastMessageAt: new Date('2024-01-13T11:15:00Z'),
    isLocked: false,
    isPinned: true,
    tags: ['api', 'design', 'backend'],
    createdAt: new Date('2024-01-08T11:30:00Z'),
    updatedAt: new Date('2024-01-13T11:15:00Z'),
  },
  'thread-4': {
    id: 'thread-4',
    title: 'Testing Strategy Review',
    content: 'Reviewing our current testing approach and identifying improvements.',
    chatChannelId: 'chat-qa-testing',
    authorId: 'user-mike',
    messageCount: 12,
    lastMessageAt: new Date('2024-01-10T15:20:00Z'),
    isLocked: true,
    isPinned: false,
    tags: ['testing', 'strategy', 'review'],
    createdAt: new Date('2024-01-07T10:45:00Z'),
    updatedAt: new Date('2024-01-10T15:20:00Z'),
  },
  'thread-5': {
    id: 'thread-5',
    title: 'Database Migration Plan',
    content: 'Planning the upcoming database schema changes and migration strategy.',
    chatChannelId: 'chat-backend-dev',
    authorId: 'user-emma',
    messageCount: 18,
    lastMessageAt: new Date('2024-01-14T09:30:00Z'),
    isLocked: false,
    isPinned: true,
    tags: ['database', 'migration', 'planning'],
    createdAt: new Date('2024-01-06T14:15:00Z'),
    updatedAt: new Date('2024-01-14T09:30:00Z'),
  },
  'thread-6': {
    id: 'thread-6',
    title: 'UI/UX Design Guidelines',
    content: 'Establishing design principles and user experience standards.',
    chatChannelId: 'chat-design',
    authorId: 'user-alex',
    messageCount: 25,
    lastMessageAt: new Date('2024-01-13T16:45:00Z'),
    isLocked: false,
    isPinned: false,
    tags: ['design', 'ui', 'ux', 'guidelines'],
    createdAt: new Date('2024-01-05T13:20:00Z'),
    updatedAt: new Date('2024-01-13T16:45:00Z'),
  },
  'thread-7': {
    id: 'thread-7',
    title: 'Security Best Practices',
    content: 'Important security considerations for our application development.',
    chatChannelId: 'chat-security',
    authorId: 'user-david',
    messageCount: 9,
    lastMessageAt: new Date('2024-01-12T08:15:00Z'),
    isLocked: false,
    isPinned: true,
    tags: ['security', 'best-practices', 'development'],
    createdAt: new Date('2024-01-04T15:30:00Z'),
    updatedAt: new Date('2024-01-12T08:15:00Z'),
  },
  'thread-8': {
    id: 'thread-8',
    title: 'Performance Optimization',
    content: 'Strategies for improving application performance and user experience.',
    chatChannelId: 'chat-performance',
    authorId: 'user-lisa',
    messageCount: 14,
    lastMessageAt: new Date('2024-01-11T12:00:00Z'),
    isLocked: false,
    isPinned: false,
    tags: ['performance', 'optimization', 'user-experience'],
    createdAt: new Date('2024-01-03T10:45:00Z'),
    updatedAt: new Date('2024-01-11T12:00:00Z'),
  },
  'thread-9': {
    id: 'thread-9',
    title: 'Code Review Guidelines',
    content: 'Best practices and standards for conducting effective code reviews.',
    chatChannelId: 'chat-team-general',
    authorId: 'user-mark',
    messageCount: 11,
    lastMessageAt: new Date('2024-01-14T14:20:00Z'),
    isLocked: false,
    isPinned: false,
    tags: ['code-review', 'guidelines', 'quality'],
    createdAt: new Date('2024-01-02T11:15:00Z'),
    updatedAt: new Date('2024-01-14T14:20:00Z'),
  },
  'thread-10': {
    id: 'thread-10',
    title: 'Deployment Process Updates',
    content: 'Changes to our deployment workflow and automation processes.',
    chatChannelId: 'chat-devops',
    authorId: 'user-anna',
    messageCount: 16,
    lastMessageAt: new Date('2024-01-13T17:30:00Z'),
    isLocked: false,
    isPinned: true,
    tags: ['deployment', 'devops', 'automation'],
    createdAt: new Date('2024-01-01T09:45:00Z'),
    updatedAt: new Date('2024-01-13T17:30:00Z'),
  },
}
