/**
 * @fileoverview gRPC-Web generated client stub for proto.api.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.1
// source: proto/api/v1/activity.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as proto_api_v1_activity_pb from '../../../proto/api/v1/activity_pb'; // proto import: "proto/api/v1/activity.proto"


export class ActivityServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetActivities = new grpcWeb.MethodDescriptor(
    '/proto.api.v1.ActivityService/GetActivities',
    grpcWeb.MethodType.UNARY,
    proto_api_v1_activity_pb.GetActivitiesRequest,
    proto_api_v1_activity_pb.GetActivitiesResponse,
    (request: proto_api_v1_activity_pb.GetActivitiesRequest) => {
      return request.serializeBinary();
    },
    proto_api_v1_activity_pb.GetActivitiesResponse.deserializeBinary
  );

  getActivities(
    request: proto_api_v1_activity_pb.GetActivitiesRequest,
    metadata?: grpcWeb.Metadata | null): Promise<proto_api_v1_activity_pb.GetActivitiesResponse>;

  getActivities(
    request: proto_api_v1_activity_pb.GetActivitiesRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_api_v1_activity_pb.GetActivitiesResponse) => void): grpcWeb.ClientReadableStream<proto_api_v1_activity_pb.GetActivitiesResponse>;

  getActivities(
    request: proto_api_v1_activity_pb.GetActivitiesRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_api_v1_activity_pb.GetActivitiesResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/proto.api.v1.ActivityService/GetActivities',
        request,
        metadata || {},
        this.methodDescriptorGetActivities,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/proto.api.v1.ActivityService/GetActivities',
    request,
    metadata || {},
    this.methodDescriptorGetActivities);
  }

  methodDescriptorCreateActivitySlot = new grpcWeb.MethodDescriptor(
    '/proto.api.v1.ActivityService/CreateActivitySlot',
    grpcWeb.MethodType.UNARY,
    proto_api_v1_activity_pb.CreateActivitySlotRequest,
    proto_api_v1_activity_pb.CreateActivitySlotResponse,
    (request: proto_api_v1_activity_pb.CreateActivitySlotRequest) => {
      return request.serializeBinary();
    },
    proto_api_v1_activity_pb.CreateActivitySlotResponse.deserializeBinary
  );

  createActivitySlot(
    request: proto_api_v1_activity_pb.CreateActivitySlotRequest,
    metadata?: grpcWeb.Metadata | null): Promise<proto_api_v1_activity_pb.CreateActivitySlotResponse>;

  createActivitySlot(
    request: proto_api_v1_activity_pb.CreateActivitySlotRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_api_v1_activity_pb.CreateActivitySlotResponse) => void): grpcWeb.ClientReadableStream<proto_api_v1_activity_pb.CreateActivitySlotResponse>;

  createActivitySlot(
    request: proto_api_v1_activity_pb.CreateActivitySlotRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_api_v1_activity_pb.CreateActivitySlotResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/proto.api.v1.ActivityService/CreateActivitySlot',
        request,
        metadata || {},
        this.methodDescriptorCreateActivitySlot,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/proto.api.v1.ActivityService/CreateActivitySlot',
    request,
    metadata || {},
    this.methodDescriptorCreateActivitySlot);
  }

  methodDescriptorDeleteActivitySlot = new grpcWeb.MethodDescriptor(
    '/proto.api.v1.ActivityService/DeleteActivitySlot',
    grpcWeb.MethodType.UNARY,
    proto_api_v1_activity_pb.DeleteActivitySlotRequest,
    proto_api_v1_activity_pb.DeleteActivitySlotResponse,
    (request: proto_api_v1_activity_pb.DeleteActivitySlotRequest) => {
      return request.serializeBinary();
    },
    proto_api_v1_activity_pb.DeleteActivitySlotResponse.deserializeBinary
  );

  deleteActivitySlot(
    request: proto_api_v1_activity_pb.DeleteActivitySlotRequest,
    metadata?: grpcWeb.Metadata | null): Promise<proto_api_v1_activity_pb.DeleteActivitySlotResponse>;

  deleteActivitySlot(
    request: proto_api_v1_activity_pb.DeleteActivitySlotRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_api_v1_activity_pb.DeleteActivitySlotResponse) => void): grpcWeb.ClientReadableStream<proto_api_v1_activity_pb.DeleteActivitySlotResponse>;

  deleteActivitySlot(
    request: proto_api_v1_activity_pb.DeleteActivitySlotRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_api_v1_activity_pb.DeleteActivitySlotResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/proto.api.v1.ActivityService/DeleteActivitySlot',
        request,
        metadata || {},
        this.methodDescriptorDeleteActivitySlot,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/proto.api.v1.ActivityService/DeleteActivitySlot',
    request,
    metadata || {},
    this.methodDescriptorDeleteActivitySlot);
  }

}

