/**
 * @fileoverview gRPC-Web generated client stub for proto.api.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.1
// source: proto/api/v1/mobile_integrity.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as proto_api_v1_mobile_integrity_pb from '../../../proto/api/v1/mobile_integrity_pb'; // proto import: "proto/api/v1/mobile_integrity.proto"


export class MobileIntegrityServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetChallenge = new grpcWeb.MethodDescriptor(
    '/proto.api.v1.MobileIntegrityService/GetChallenge',
    grpcWeb.MethodType.UNARY,
    proto_api_v1_mobile_integrity_pb.GetChallengeRequest,
    proto_api_v1_mobile_integrity_pb.GetChallengeResponse,
    (request: proto_api_v1_mobile_integrity_pb.GetChallengeRequest) => {
      return request.serializeBinary();
    },
    proto_api_v1_mobile_integrity_pb.GetChallengeResponse.deserializeBinary
  );

  getChallenge(
    request: proto_api_v1_mobile_integrity_pb.GetChallengeRequest,
    metadata?: grpcWeb.Metadata | null): Promise<proto_api_v1_mobile_integrity_pb.GetChallengeResponse>;

  getChallenge(
    request: proto_api_v1_mobile_integrity_pb.GetChallengeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_api_v1_mobile_integrity_pb.GetChallengeResponse) => void): grpcWeb.ClientReadableStream<proto_api_v1_mobile_integrity_pb.GetChallengeResponse>;

  getChallenge(
    request: proto_api_v1_mobile_integrity_pb.GetChallengeRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_api_v1_mobile_integrity_pb.GetChallengeResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/proto.api.v1.MobileIntegrityService/GetChallenge',
        request,
        metadata || {},
        this.methodDescriptorGetChallenge,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/proto.api.v1.MobileIntegrityService/GetChallenge',
    request,
    metadata || {},
    this.methodDescriptorGetChallenge);
  }

  methodDescriptorGetMobileConfig = new grpcWeb.MethodDescriptor(
    '/proto.api.v1.MobileIntegrityService/GetMobileConfig',
    grpcWeb.MethodType.UNARY,
    proto_api_v1_mobile_integrity_pb.GetMobileConfigRequest,
    proto_api_v1_mobile_integrity_pb.GetMobileConfigResponse,
    (request: proto_api_v1_mobile_integrity_pb.GetMobileConfigRequest) => {
      return request.serializeBinary();
    },
    proto_api_v1_mobile_integrity_pb.GetMobileConfigResponse.deserializeBinary
  );

  getMobileConfig(
    request: proto_api_v1_mobile_integrity_pb.GetMobileConfigRequest,
    metadata?: grpcWeb.Metadata | null): Promise<proto_api_v1_mobile_integrity_pb.GetMobileConfigResponse>;

  getMobileConfig(
    request: proto_api_v1_mobile_integrity_pb.GetMobileConfigRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_api_v1_mobile_integrity_pb.GetMobileConfigResponse) => void): grpcWeb.ClientReadableStream<proto_api_v1_mobile_integrity_pb.GetMobileConfigResponse>;

  getMobileConfig(
    request: proto_api_v1_mobile_integrity_pb.GetMobileConfigRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_api_v1_mobile_integrity_pb.GetMobileConfigResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/proto.api.v1.MobileIntegrityService/GetMobileConfig',
        request,
        metadata || {},
        this.methodDescriptorGetMobileConfig,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/proto.api.v1.MobileIntegrityService/GetMobileConfig',
    request,
    metadata || {},
    this.methodDescriptorGetMobileConfig);
  }

}

