/**
 * @fileoverview gRPC-Web generated client stub for proto.api.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.1
// source: proto/api/v1/payment-gateway-webhooks.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as proto_api_v1_payment$gateway$webhooks_pb from '../../../proto/api/v1/payment-gateway-webhooks_pb'; // proto import: "proto/api/v1/payment-gateway-webhooks.proto"


export class PaymentGatewayWebhooksClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorProcessStripeWebhook = new grpcWeb.MethodDescriptor(
    '/proto.api.v1.PaymentGatewayWebhooks/ProcessStripeWebhook',
    grpcWeb.MethodType.UNARY,
    proto_api_v1_payment$gateway$webhooks_pb.StripeWebhookRequest,
    proto_api_v1_payment$gateway$webhooks_pb.StripeWebhookResponse,
    (request: proto_api_v1_payment$gateway$webhooks_pb.StripeWebhookRequest) => {
      return request.serializeBinary();
    },
    proto_api_v1_payment$gateway$webhooks_pb.StripeWebhookResponse.deserializeBinary
  );

  processStripeWebhook(
    request: proto_api_v1_payment$gateway$webhooks_pb.StripeWebhookRequest,
    metadata?: grpcWeb.Metadata | null): Promise<proto_api_v1_payment$gateway$webhooks_pb.StripeWebhookResponse>;

  processStripeWebhook(
    request: proto_api_v1_payment$gateway$webhooks_pb.StripeWebhookRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_api_v1_payment$gateway$webhooks_pb.StripeWebhookResponse) => void): grpcWeb.ClientReadableStream<proto_api_v1_payment$gateway$webhooks_pb.StripeWebhookResponse>;

  processStripeWebhook(
    request: proto_api_v1_payment$gateway$webhooks_pb.StripeWebhookRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_api_v1_payment$gateway$webhooks_pb.StripeWebhookResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/proto.api.v1.PaymentGatewayWebhooks/ProcessStripeWebhook',
        request,
        metadata || {},
        this.methodDescriptorProcessStripeWebhook,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/proto.api.v1.PaymentGatewayWebhooks/ProcessStripeWebhook',
    request,
    metadata || {},
    this.methodDescriptorProcessStripeWebhook);
  }

}

