/**
 * @fileoverview gRPC-Web generated client stub for proto.api.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.1
// source: proto/api/v1/telemetry.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as google_api_httpbody_pb from '../../../google/api/httpbody_pb'; // proto import: "google/api/httpbody.proto"


export class TelemetryServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorProxy = new grpcWeb.MethodDescriptor(
    '/proto.api.v1.TelemetryService/Proxy',
    grpcWeb.MethodType.UNARY,
    google_api_httpbody_pb.HttpBody,
    google_api_httpbody_pb.HttpBody,
    (request: google_api_httpbody_pb.HttpBody) => {
      return request.serializeBinary();
    },
    google_api_httpbody_pb.HttpBody.deserializeBinary
  );

  proxy(
    request: google_api_httpbody_pb.HttpBody,
    metadata?: grpcWeb.Metadata | null): Promise<google_api_httpbody_pb.HttpBody>;

  proxy(
    request: google_api_httpbody_pb.HttpBody,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_api_httpbody_pb.HttpBody) => void): grpcWeb.ClientReadableStream<google_api_httpbody_pb.HttpBody>;

  proxy(
    request: google_api_httpbody_pb.HttpBody,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_api_httpbody_pb.HttpBody) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/proto.api.v1.TelemetryService/Proxy',
        request,
        metadata || {},
        this.methodDescriptorProxy,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/proto.api.v1.TelemetryService/Proxy',
    request,
    metadata || {},
    this.methodDescriptorProxy);
  }

}

