/**
 * @fileoverview gRPC-Web generated client stub for proto.api.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.1
// source: proto/api/v1/waiting_list.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as proto_api_v1_waiting_list_pb from '../../../proto/api/v1/waiting_list_pb'; // proto import: "proto/api/v1/waiting_list.proto"


export class WaitingListServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorJoinWaitingList = new grpcWeb.MethodDescriptor(
    '/proto.api.v1.WaitingListService/JoinWaitingList',
    grpcWeb.MethodType.UNARY,
    proto_api_v1_waiting_list_pb.JoinWaitingListRequest,
    proto_api_v1_waiting_list_pb.JoinWaitingListResponse,
    (request: proto_api_v1_waiting_list_pb.JoinWaitingListRequest) => {
      return request.serializeBinary();
    },
    proto_api_v1_waiting_list_pb.JoinWaitingListResponse.deserializeBinary
  );

  joinWaitingList(
    request: proto_api_v1_waiting_list_pb.JoinWaitingListRequest,
    metadata?: grpcWeb.Metadata | null): Promise<proto_api_v1_waiting_list_pb.JoinWaitingListResponse>;

  joinWaitingList(
    request: proto_api_v1_waiting_list_pb.JoinWaitingListRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_api_v1_waiting_list_pb.JoinWaitingListResponse) => void): grpcWeb.ClientReadableStream<proto_api_v1_waiting_list_pb.JoinWaitingListResponse>;

  joinWaitingList(
    request: proto_api_v1_waiting_list_pb.JoinWaitingListRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_api_v1_waiting_list_pb.JoinWaitingListResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/proto.api.v1.WaitingListService/JoinWaitingList',
        request,
        metadata || {},
        this.methodDescriptorJoinWaitingList,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/proto.api.v1.WaitingListService/JoinWaitingList',
    request,
    metadata || {},
    this.methodDescriptorJoinWaitingList);
  }

  methodDescriptorListUsers = new grpcWeb.MethodDescriptor(
    '/proto.api.v1.WaitingListService/ListUsers',
    grpcWeb.MethodType.UNARY,
    proto_api_v1_waiting_list_pb.ListUsersRequest,
    proto_api_v1_waiting_list_pb.ListUsersResponse,
    (request: proto_api_v1_waiting_list_pb.ListUsersRequest) => {
      return request.serializeBinary();
    },
    proto_api_v1_waiting_list_pb.ListUsersResponse.deserializeBinary
  );

  listUsers(
    request: proto_api_v1_waiting_list_pb.ListUsersRequest,
    metadata?: grpcWeb.Metadata | null): Promise<proto_api_v1_waiting_list_pb.ListUsersResponse>;

  listUsers(
    request: proto_api_v1_waiting_list_pb.ListUsersRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_api_v1_waiting_list_pb.ListUsersResponse) => void): grpcWeb.ClientReadableStream<proto_api_v1_waiting_list_pb.ListUsersResponse>;

  listUsers(
    request: proto_api_v1_waiting_list_pb.ListUsersRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_api_v1_waiting_list_pb.ListUsersResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/proto.api.v1.WaitingListService/ListUsers',
        request,
        metadata || {},
        this.methodDescriptorListUsers,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/proto.api.v1.WaitingListService/ListUsers',
    request,
    metadata || {},
    this.methodDescriptorListUsers);
  }

}

