name: CI-expo

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  schedule:
    - cron: "0 0 * * *" # Every day at midnight UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref }}
  cancel-in-progress: true

jobs:
  expo-checks:
    uses: zondax/_workflows/.github/workflows/_checks-expo.yaml@main
    with:
      package_manager: pnpm
      github_app_auth: true
      github_app_repos: ks-frontend,web-golem
      test_command: "test:expo"
      coverage_command: "test:expo:coverage"
    secrets:
      app_id: ${{ secrets.PULUMI_GOLEM_APP_ID }}
      app_pem: ${{ secrets.PULUMI_GOLEM_APP_PEM }}
