name: CI-expo

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  schedule:
    - cron: "0 0 * * *" # Every day at midnight UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref }}
  cancel-in-progress: true

jobs:
  expo-checks:
    uses: zondax/_workflows/.github/workflows/_checks-expo.yaml@v0.1.0
    with:
      package_manager: pnpm
